---
title: Filtering
---




<div id="filtering" class="section level1">
<h1>Filtering</h1>
<p>We will focus on working with our data more. At this point we will consider how we pick the rows of the data that we wish to work with. If you consider many modern data sets, we have so much information that we may not want to bring it all in at once.</p>
<p>We have not discussed exactly how R works at this point, however R brings data into the RAM of your computer. This means you can be limited for what size data you can bring in at once. Very rarely do you need the entire data set. We will focus on how to pick the rows or observations we want now.</p>
<div id="enter-the-filter-function" class="section level2">
<h2>Enter the <code>filter()</code> Function</h2>
<p>The <code>filter()</code> function chooses rows that meet a specific criteria. We can do this with Base R functions or with dplyr`.</p>
<p>Let’s say that we want to look at the flights data but we are only interested in the data from the first day of the year. We could do this without learning a new command and use indexing which we learned in <a href="http://statseducation.com/Introduction-to-R/modules/getting%20data/dataframes/">dataframes</a>:</p>
<pre class="r"><code>flights[flights$month==1 &amp; flights$day==1, ]</code></pre>
<pre><code>## # A tibble: 842 × 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1   2013     1     1      517            515         2      830
## 2   2013     1     1      533            529         4      850
## 3   2013     1     1      542            540         2      923
## 4   2013     1     1      544            545        -1     1004
## 5   2013     1     1      554            600        -6      812
## 6   2013     1     1      554            558        -4      740
## 7   2013     1     1      555            600        -5      913
## 8   2013     1     1      557            600        -3      709
## 9   2013     1     1      557            600        -3      838
## 10  2013     1     1      558            600        -2      753
## # ... with 832 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>Now this is not very difficult to do, what we have is that we are working with <code>flights</code> and we only want to keep the rows of data there <code>month==1</code> and <code>day==1</code>. However we could use the <code>filter()</code> function to do this in a much easier to read format:</p>
<pre><code>filter(.data, ...)</code></pre>
<p>where</p>
<ul>
<li><code>.data</code> is a tibble.</li>
<li><code>...</code> is a set of arguments the data you want returned needs to meet.</li>
</ul>
<p>This means in our example we could perform the following:</p>
<pre class="r"><code>filter(flights, month==1, day==1)</code></pre>
<pre><code>## # A tibble: 842 × 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1   2013     1     1      517            515         2      830
## 2   2013     1     1      533            529         4      850
## 3   2013     1     1      542            540         2      923
## 4   2013     1     1      544            545        -1     1004
## 5   2013     1     1      554            600        -6      812
## 6   2013     1     1      554            558        -4      740
## 7   2013     1     1      555            600        -5      913
## 8   2013     1     1      557            600        -3      709
## 9   2013     1     1      557            600        -3      838
## 10  2013     1     1      558            600        -2      753
## # ... with 832 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>We could instead do the same command with piping to make it even easier to read:</p>
<pre><code>flights %&gt;%
    filter(month==1, day==1)</code></pre>
<p>Finally we could also only do one filtering at a time and chain it:</p>
<pre><code>flights %&gt;%
    filter(month==1) %&gt;%
    filter(day==1)</code></pre>
<p>These will all lead to the same output. <strong><em>Make sure you verify this on your own screen</em></strong>.</p>
</div>
<div id="further-filtering" class="section level2">
<h2>Further Filtering</h2>
<p><code>filter()</code> supports the use of multiple conditions where we can use Boolean. For example if we wanted to consider only flights that depart between 0600 and 0605 we could do the following:</p>
<pre class="r"><code>flights %&gt;% filter(dep_time &gt;= 600, dep_time &lt;= 605)</code></pre>
<pre><code>## # A tibble: 2,460 × 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1   2013     1     1      600            600         0      851
## 2   2013     1     1      600            600         0      837
## 3   2013     1     1      601            600         1      844
## 4   2013     1     1      602            610        -8      812
## 5   2013     1     1      602            605        -3      821
## 6   2013     1     2      600            600         0      814
## 7   2013     1     2      600            605        -5      751
## 8   2013     1     2      600            600         0      819
## 9   2013     1     2      600            600         0      846
## 10  2013     1     2      600            600         0      737
## # ... with 2,450 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>We would then get 2,460 different flights. Another way to accomplish this would be to use what is called a helper function. We can use <code>between()</code> which lets us pick specific numeric ranges:</p>
<pre><code>flights %&gt;%
  filter(between(dep_time,600,605))</code></pre>
<p>We can also use the <code>filter()</code> function to remove missing data for us. Previously we learned about a class of functions called <code>is.</code><em>foo</em><code>()</code> where <em>foo</em> represents a data type. We could choose to only use flights that have a departure time. That means we wish to not have missing data for departure time:</p>
<pre class="r"><code>flights %&gt;% filter(!is.na(dep_time))</code></pre>
<pre><code>## # A tibble: 328,521 × 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1   2013     1     1      517            515         2      830
## 2   2013     1     1      533            529         4      850
## 3   2013     1     1      542            540         2      923
## 4   2013     1     1      544            545        -1     1004
## 5   2013     1     1      554            600        -6      812
## 6   2013     1     1      554            558        -4      740
## 7   2013     1     1      555            600        -5      913
## 8   2013     1     1      557            600        -3      709
## 9   2013     1     1      557            600        -3      838
## 10  2013     1     1      558            600        -2      753
## # ... with 328,511 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<div class="content-box-green">
<h1>
On Your Own: RStudio Practice
</h1>
<p>Using the <code>filter()</code> function and chaining:</p>
<ul>
<li>Choose only rows associated with</li>
<li>United Airlines (UA)</li>
<li>American Airlines (AA)</li>
</ul>
<p>Your end result should be:</p>
<pre><code>## # A tibble: 91,394 × 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1   2013     1     1      517            515         2      830
## 2   2013     1     1      533            529         4      850
## 3   2013     1     1      542            540         2      923
## 4   2013     1     1      554            558        -4      740
## 5   2013     1     1      558            600        -2      753
## 6   2013     1     1      558            600        -2      924
## 7   2013     1     1      558            600        -2      923
## 8   2013     1     1      559            600        -1      941
## 9   2013     1     1      559            600        -1      854
## 10  2013     1     1      606            610        -4      858
## # ... with 91,384 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


