---
title: Joins
---


<div id="joins" class="section level1">
<h1>Joins</h1>
<div id="credit-where-credit-is-due" class="section level2">
<h2>Credit Where Credit is Due</h2>
<p>The following is a cheatsheet created by <a href="https://www.stat.ubc.ca/~jenny/">Jenny Bryan</a> and her course <a href="stat545.com">Stat 545</a>. You may wonder why this resourse is directly from another course, but here is the reason. This is hands down the best explanation for using joins that we have seen. As soon as we come up with something better it will be posted and you won’t see this!</p>
<div id="why-the-cheatsheet" class="section level3">
<h3>Why the cheatsheet</h3>
<ul>
<li>Examples for those of us who don’t speak SQL so good. There are lots of <a href="//encrypted.google.com/search?q=sql+join&amp;tbm=isch">Venn diagrams re: SQL joins on the interwebs</a>, but I wanted R examples.</li>
<li><a href="http://www.rdocumentation.org/packages/dplyr">Full documentation</a> for the dplyr package, which is developed by Hadley Wickham and Romain Francois on <a href="https://github.com/hadley/dplyr">GitHub</a>.</li>
<li>The <a href="https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html">vignette on Two-table verbs</a> covers the joins shown here.</li>
</ul>
</div>
</div>
<div id="the-data" class="section level2">
<h2>The Data</h2>
<p>We will be Working with two small data.frames, <code>superheroes</code> and <code>publishers</code>.</p>
<pre class="r"><code>suppressPackageStartupMessages(library(dplyr))
library(readr)

superheroes &lt;- &quot;
    name, alignment, gender,         publisher
 Magneto,       bad,   male,            Marvel
   Storm,      good, female,            Marvel
Mystique,       bad, female,            Marvel
  Batman,      good,   male,                DC
   Joker,       bad,   male,                DC
Catwoman,       bad, female,                DC
 Hellboy,      good,   male, Dark Horse Comics
&quot;
superheroes &lt;- read_csv(superheroes, trim_ws = TRUE, skip = 1)

publishers &lt;- &quot;
  publisher, yr_founded
         DC,       1934
     Marvel,       1939
      Image,       1992
&quot;
publishers &lt;- read_csv(publishers, trim_ws = TRUE, skip = 1)</code></pre>
<div id="inner_joinsuperheroes-publishers" class="section level3">
<h3>inner_join(superheroes, publishers)</h3>
<blockquote>
<p>inner_join(x, y): Return all rows from x where there are matching values in y, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned. This is a mutating join.</p>
</blockquote>
<pre class="r"><code>(ijsp &lt;- inner_join(superheroes, publishers))</code></pre>
<pre><code>## # A tibble: 6 × 5
##       name alignment gender publisher yr_founded
##      &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;      &lt;int&gt;
## 1  Magneto       bad   male    Marvel       1939
## 2    Storm      good female    Marvel       1939
## 3 Mystique       bad female    Marvel       1939
## 4   Batman      good   male        DC       1934
## 5    Joker       bad   male        DC       1934
## 6 Catwoman       bad female        DC       1934</code></pre>
<p>We lose Hellboy in the join because, although he appears in <code>x = superheroes</code>, his publisher Dark Horse Comics does not appear in <code>y = publishers</code>. The join result has all variables from <code>x = superheroes</code> plus <code>yr_founded</code>, from <code>y</code>.</p>
<table border="1">
<tr>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>inner_join(x = superheroes, y = publishers)</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="semi_joinsuperheroes-publishers" class="section level3">
<h3>semi_join(superheroes, publishers)</h3>
<blockquote>
<p>semi_join(x, y): Return all rows from x where there are matching values in y, keeping just columns from x. A semi join differs from an inner join because an inner join will return one row of x for each matching row of y, where a semi join will never duplicate rows of x. This is a filtering join.</p>
</blockquote>
<pre class="r"><code>(sjsp &lt;- semi_join(superheroes, publishers))</code></pre>
<pre><code>## # A tibble: 6 × 4
##       name alignment gender publisher
##      &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;
## 1   Batman      good   male        DC
## 2    Joker       bad   male        DC
## 3 Catwoman       bad female        DC
## 4  Magneto       bad   male    Marvel
## 5    Storm      good female    Marvel
## 6 Mystique       bad female    Marvel</code></pre>
<p>We get a similar result as with <code>inner_join()</code> but the join result contains only the variables originally found in <code>x = superheroes</code>. But note the row order has changed.</p>
<table border="1">
<tr>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>semi-join(x = superheroes, y = publishers)</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="left_joinsuperheroes-publishers" class="section level3">
<h3>left_join(superheroes, publishers)</h3>
<blockquote>
<p>left_join(x, y): Return all rows from x, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned. This is a mutating join.</p>
</blockquote>
<pre class="r"><code>(ljsp &lt;- left_join(superheroes, publishers))</code></pre>
<pre><code>## # A tibble: 7 × 5
##       name alignment gender         publisher yr_founded
##      &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;             &lt;chr&gt;      &lt;int&gt;
## 1  Magneto       bad   male            Marvel       1939
## 2    Storm      good female            Marvel       1939
## 3 Mystique       bad female            Marvel       1939
## 4   Batman      good   male                DC       1934
## 5    Joker       bad   male                DC       1934
## 6 Catwoman       bad female                DC       1934
## 7  Hellboy      good   male Dark Horse Comics         NA</code></pre>
<p>We basically get <code>x = superheroes</code> back, but with the addition of variable <code>yr_founded</code>, which is unique to <code>y = publishers</code>. Hellboy, whose publisher does not appear in <code>y = publishers</code>, has an <code>NA</code> for <code>yr_founded</code>.</p>
<table border="1">
<tr>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>left_join(x = superheroes, y = publishers)</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="anti_joinsuperheroes-publishers" class="section level3">
<h3>anti_join(superheroes, publishers)</h3>
<blockquote>
<p>anti_join(x, y): Return all rows from x where there are not matching values in y, keeping just columns from x. This is a filtering join.</p>
</blockquote>
<pre class="r"><code>(ajsp &lt;- anti_join(superheroes, publishers))</code></pre>
<pre><code>## # A tibble: 1 × 4
##      name alignment gender         publisher
##     &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;             &lt;chr&gt;
## 1 Hellboy      good   male Dark Horse Comics</code></pre>
<p>We keep <strong>only</strong> Hellboy now (and do not get <code>yr_founded</code>).</p>
<table border="1">
<tr>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>anti_join(x = superheroes, y = publishers)</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="inner_joinpublishers-superheroes" class="section level3">
<h3>inner_join(publishers, superheroes)</h3>
<blockquote>
<p>inner_join(x, y): Return all rows from x where there are matching values in y, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned. This is a mutating join.</p>
</blockquote>
<pre class="r"><code>(ijps &lt;- inner_join(publishers, superheroes))</code></pre>
<pre><code>## # A tibble: 6 × 5
##   publisher yr_founded     name alignment gender
##       &lt;chr&gt;      &lt;int&gt;    &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;
## 1        DC       1934   Batman      good   male
## 2        DC       1934    Joker       bad   male
## 3        DC       1934 Catwoman       bad female
## 4    Marvel       1939  Magneto       bad   male
## 5    Marvel       1939    Storm      good female
## 6    Marvel       1939 Mystique       bad female</code></pre>
<p>In a way, this does illustrate multiple matches, if you think about it from the <code>x = publishers</code> direction. Every publisher that has a match in <code>y = superheroes</code> appears multiple times in the result, once for each match. In fact, we’re getting the same result as with <code>inner_join(superheroes, publishers)</code>, up to variable order (which you should also never rely on in an analysis).</p>
<table border="1">
<tr>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>inner_join(x = publishers, y = superheroes)</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
</tr>
<tr class="even">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
</tr>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
</tr>
<tr class="odd">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="semi_joinpublishers-superheroes" class="section level3">
<h3>semi_join(publishers, superheroes)</h3>
<blockquote>
<p>semi_join(x, y): Return all rows from x where there are matching values in y, keeping just columns from x. A semi join differs from an inner join because an inner join will return one row of x for each matching row of y, where a semi join will never duplicate rows of x. This is a filtering join.</p>
</blockquote>
<pre class="r"><code>(sjps &lt;- semi_join(x = publishers, y = superheroes))</code></pre>
<pre><code>## # A tibble: 2 × 2
##   publisher yr_founded
##       &lt;chr&gt;      &lt;int&gt;
## 1    Marvel       1939
## 2        DC       1934</code></pre>
<p>Now the effects of switching the <code>x</code> and <code>y</code> roles is more clear. The result resembles <code>x = publishers</code>, but the publisher Image is lost, because there are no observations where <code>publisher == &quot;Image&quot;</code> in <code>y = superheroes</code>.</p>
<table border="1">
<tr>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>semi-join(x = publishers, y = superheroes)</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="left_joinpublishers-superheroes" class="section level3">
<h3>left_join(publishers, superheroes)</h3>
<blockquote>
<p>left_join(x, y): Return all rows from x, and all columns from x and y. If there are multiple matches between x and y, all combination of the matches are returned. This is a mutating join.</p>
</blockquote>
<pre class="r"><code>(ljps &lt;- left_join(publishers, superheroes))</code></pre>
<pre><code>## # A tibble: 7 × 5
##   publisher yr_founded     name alignment gender
##       &lt;chr&gt;      &lt;int&gt;    &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;
## 1        DC       1934   Batman      good   male
## 2        DC       1934    Joker       bad   male
## 3        DC       1934 Catwoman       bad female
## 4    Marvel       1939  Magneto       bad   male
## 5    Marvel       1939    Storm      good female
## 6    Marvel       1939 Mystique       bad female
## 7     Image       1992     &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;</code></pre>
<p>We get a similar result as with <code>inner_join()</code> but the publisher Image survives in the join, even though no superheroes from Image appear in <code>y = superheroes</code>. As a result, Image has <code>NA</code>s for <code>name</code>, <code>alignment</code>, and <code>gender</code>.</p>
<table border="1">
<tr>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>left_join(x = publishers, y = superheroes)</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
</tr>
<tr class="even">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
</tr>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
</tr>
<tr class="odd">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="anti_joinpublishers-superheroes" class="section level3">
<h3>anti_join(publishers, superheroes)</h3>
<blockquote>
<p>anti_join(x, y): Return all rows from x where there are not matching values in y, keeping just columns from x. This is a filtering join.</p>
</blockquote>
<pre class="r"><code>(ajps &lt;- anti_join(publishers, superheroes))</code></pre>
<pre><code>## # A tibble: 1 × 2
##   publisher yr_founded
##       &lt;chr&gt;      &lt;int&gt;
## 1     Image       1992</code></pre>
<p>We keep <strong>only</strong> publisher Image now (and the variables found in <code>x = publishers</code>).</p>
<table border="1">
<tr>
<tr>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>anti_join(x = publishers, y = superheroes)</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
<div id="full_joinsuperheroes-publishers" class="section level3">
<h3>full_join(superheroes, publishers)</h3>
<blockquote>
<p>full_join(x, y): Return all rows and all columns from both x and y. Where there are not matching values, returns NA for the one missing. This is a mutating join.</p>
</blockquote>
<pre class="r"><code>(fjsp &lt;- full_join(superheroes, publishers))</code></pre>
<pre><code>## # A tibble: 8 × 5
##       name alignment gender         publisher yr_founded
##      &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;             &lt;chr&gt;      &lt;int&gt;
## 1  Magneto       bad   male            Marvel       1939
## 2    Storm      good female            Marvel       1939
## 3 Mystique       bad female            Marvel       1939
## 4   Batman      good   male                DC       1934
## 5    Joker       bad   male                DC       1934
## 6 Catwoman       bad female                DC       1934
## 7  Hellboy      good   male Dark Horse Comics         NA
## 8     &lt;NA&gt;      &lt;NA&gt;   &lt;NA&gt;             Image       1992</code></pre>
<p>We get all rows of <code>x = superheroes</code> plus a new row from <code>y = publishers</code>, containing the publisher Image. We get all variables from <code>x = superheroes</code> AND all variables from <code>y = publishers</code>. Any row that derives solely from one table or the other carries <code>NA</code>s in the variables found only in the other table.</p>
<table border="1">
<tr>
<td valign="top">
<p>superheroes</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>publishers</p>
<table>
<thead>
<tr class="header">
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
<td valign="top">
<p>full_join(x = superheroes, y = publishers)</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="left">alignment</th>
<th align="left">gender</th>
<th align="left">publisher</th>
<th align="right">yr_founded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Magneto</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Storm</td>
<td align="left">good</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="odd">
<td align="left">Mystique</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">Marvel</td>
<td align="right">1939</td>
</tr>
<tr class="even">
<td align="left">Batman</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="odd">
<td align="left">Joker</td>
<td align="left">bad</td>
<td align="left">male</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="even">
<td align="left">Catwoman</td>
<td align="left">bad</td>
<td align="left">female</td>
<td align="left">DC</td>
<td align="right">1934</td>
</tr>
<tr class="odd">
<td align="left">Hellboy</td>
<td align="left">good</td>
<td align="left">male</td>
<td align="left">Dark Horse Comics</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">Image</td>
<td align="right">1992</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>