---
title: Adding Variables
---




<div id="adding-new-variables" class="section level1">
<h1>Adding New Variables</h1>
<p>There is usually no way around needing a new variable in your data. For example, most medical studies have height and weight in them, however many times what a researcher is interested in using is Body Mass Index (BMI). We would need to add BMI in.</p>
<p>Using the <code>tidyverse</code> we can add new variables in multiple ways</p>
<ul>
<li><code>mutate()</code></li>
<li><code>transmute()</code></li>
</ul>
<p>With <code>mutate()</code> we have</p>
<pre><code>mutate(.data, ...)</code></pre>
<p>where</p>
<ul>
<li><code>.data</code> is your tibble of interest.</li>
<li><code>...</code> is the name paired with an expression</li>
</ul>
<p>Then with <code>transmute()</code> we have:</p>
<pre><code>transmute(.data, ...)</code></pre>
<p>where</p>
<ul>
<li><code>.data</code> is your tibble of interest.</li>
<li><code>...</code> is the name paired with an expression</li>
</ul>
<div id="differences-between-mutate-and-transmute" class="section level2">
<h2>Differences Between <code>mutate()</code> and <code>transmute()</code></h2>
<p>There is only one major difference between <code>mutate()</code> and <code>transmutate</code> and that is what it keeps in your data.</p>
<ul>
<li><code>mutate()</code>
<ul>
<li>creates a new variable</li>
<li>It keeps all existing variables</li>
</ul></li>
<li><code>transmute()</code></li>
<li>creates a new variable.</li>
<li>It only keeps the new variables</li>
</ul>
</div>
<div id="example" class="section level2">
<h2>Example</h2>
<p>Let’s say we wish to have a variable called speed. We want to basically do:</p>
<p><span class="math display">\[\text{speed} = \dfrac{\text{distance}}{\text{time}}*60\]</span></p>
<p>We can first do this with <code>mutate()</code>:</p>
<pre class="r"><code>flights %&gt;% 
  select(flight, distance, air_time) %&gt;%
  mutate(speed = distance/air_time*60)</code></pre>
<pre><code>## # A tibble: 336,776 × 4
##    flight distance air_time    speed
##     &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1    1545     1400      227 370.0441
## 2    1714     1416      227 374.2731
## 3    1141     1089      160 408.3750
## 4     725     1576      183 516.7213
## 5     461      762      116 394.1379
## 6    1696      719      150 287.6000
## 7     507     1065      158 404.4304
## 8    5708      229       53 259.2453
## 9      79      944      140 404.5714
## 10    301      733      138 318.6957
## # ... with 336,766 more rows</code></pre>
<p>Notice with <code>mutate()</code> we kept all of the variables we selected and added speed to this. Now we can do the same with <code>transmute()</code>:</p>
<pre class="r"><code>flights %&gt;%
  select(flight, distance, air_time) %&gt;%
  transmute(speed = distance/air_time*60)</code></pre>
<pre><code>## # A tibble: 336,776 × 1
##       speed
##       &lt;dbl&gt;
## 1  370.0441
## 2  374.2731
## 3  408.3750
## 4  516.7213
## 5  394.1379
## 6  287.6000
## 7  404.4304
## 8  259.2453
## 9  404.5714
## 10 318.6957
## # ... with 336,766 more rows</code></pre>
<p>In this example we have only kept speed.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
