---
  title: Dataframes in R!
---

<div id="dataframes-in-r" class="section level1">
<h1>Dataframes in R</h1>
<p>With statistics we are most likely to use the data structure called a data frame. This is similar to a matrix in appearance however we can have multiple types of data in it like a list. Each column must contain the same type of data or R will most likely default to character for that column. It is very important that you become proficient in working with data frames in order to fully understand data analysis.</p>
<div id="creating-data-frames" class="section level2">
<h2>Creating Data Frames</h2>
<p>We usually create a data frame with vectors.</p>
<pre class="r"><code>names &lt;- c(&quot;Angela&quot;, &quot;Shondra&quot;)
ages &lt;- c(27,36)
insurance &lt;- c(TRUE, T)
patients &lt;- data.frame(names, ages, insurance)
patients</code></pre>
<pre><code>##     names ages insurance
## 1  Angela   27      TRUE
## 2 Shondra   36      TRUE</code></pre>
<p>We may wish to add rows or columns to our data. We can do this with:</p>
<ul>
<li><strong><em>rbind()</em></strong></li>
<li><strong><em>cbind()</em></strong></li>
</ul>
<p>For example we can go back to our patient data and say we wish to add another patient we could just do the following</p>
<pre class="r"><code>l &lt;- c(names=&quot;Liu Jie&quot;, age=45, insurance=TRUE)
rbind(patients, l)</code></pre>
<pre><code>## Warning in `[&lt;-.factor`(`*tmp*`, ri, value = &quot;Liu Jie&quot;): invalid factor
## level, NA generated</code></pre>
<pre><code>##     names ages insurance
## 1  Angela   27      TRUE
## 2 Shondra   36      TRUE
## 3    &lt;NA&gt;   45      TRUE</code></pre>
<p>This warning serves as a reminder to always know what your data type is. R has read our data in as a factor when we want it as a character.</p>
<pre class="r"><code>patients$names &lt;- as.character(patients$names)
patients &lt;- rbind(patients, l)
patients</code></pre>
<pre><code>##     names ages insurance
## 1  Angela   27      TRUE
## 2 Shondra   36      TRUE
## 3 Liu Jie   45      TRUE</code></pre>
<p>Finally if we decided to then place another column of data in we could</p>
<pre class="r"><code># Next appointments
next.appt &lt;- c(&quot;09/23/2016&quot;, &quot;04/14/2016&quot;, &quot;02/25/2016&quot;)

#Lets R know these are dates
next.appt &lt;- as.Date(next.appt, &quot;%m/%d/%Y&quot;)
next.appt</code></pre>
<pre><code>## [1] &quot;2016-09-23&quot; &quot;2016-04-14&quot; &quot;2016-02-25&quot;</code></pre>
<p>We then have a vector of dates which we can <code>cbind</code> in R.</p>
<pre class="r"><code>patients &lt;- cbind(patients, next.appt)
patients</code></pre>
<pre><code>##     names ages insurance  next.appt
## 1  Angela   27      TRUE 2016-09-23
## 2 Shondra   36      TRUE 2016-04-14
## 3 Liu Jie   45      TRUE 2016-02-25</code></pre>
</div>
<div id="accessing-data-frames" class="section level2">
<h2>Accessing Data Frames</h2>
<p>In order to best consider accessing of data frames we will use some built in data from R.</p>
<pre class="r"><code>library(datasets)
titanic &lt;- data.frame(Titanic)</code></pre>
<p>We can look at the different columns that we have in the data set:</p>
<pre class="r"><code>colnames(titanic)</code></pre>
<pre><code>## [1] &quot;Class&quot;    &quot;Sex&quot;      &quot;Age&quot;      &quot;Survived&quot; &quot;Freq&quot;</code></pre>
<p>We can use the notion of indexing that we did with arrays to look at the first 2 rows of data:</p>
<pre class="r"><code>titanic[1:2,]</code></pre>
<pre><code>##   Class  Sex   Age Survived Freq
## 1   1st Male Child       No    0
## 2   2nd Male Child       No    0</code></pre>
<p>A simple function for looking at the start of the data is the <code>head()</code> function:</p>
<pre class="r"><code>head(titanic)</code></pre>
<pre><code>##   Class    Sex   Age Survived Freq
## 1   1st   Male Child       No    0
## 2   2nd   Male Child       No    0
## 3   3rd   Male Child       No   35
## 4  Crew   Male Child       No    0
## 5   1st Female Child       No    0
## 6   2nd Female Child       No    0</code></pre>
<p>We can also look at the last few rows as well</p>
<pre class="r"><code>tail(titanic)</code></pre>
<pre><code>##    Class    Sex   Age Survived Freq
## 27   3rd   Male Adult      Yes   75
## 28  Crew   Male Adult      Yes  192
## 29   1st Female Adult      Yes  140
## 30   2nd Female Adult      Yes   80
## 31   3rd Female Adult      Yes   76
## 32  Crew Female Adult      Yes   20</code></pre>
<p>If we wished to access the age information, we could do this by the column number:</p>
<pre class="r"><code>titanic[,3]</code></pre>
<pre><code>##  [1] Child Child Child Child Child Child Child Child Adult Adult Adult
## [12] Adult Adult Adult Adult Adult Child Child Child Child Child Child
## [23] Child Child Adult Adult Adult Adult Adult Adult Adult Adult
## Levels: Child Adult</code></pre>
<p>or more frequently we would use the column name instead:</p>
<pre class="r"><code>titanic[, &quot;Age&quot;]</code></pre>
<pre><code>##  [1] Child Child Child Child Child Child Child Child Adult Adult Adult
## [12] Adult Adult Adult Adult Adult Child Child Child Child Child Child
## [23] Child Child Adult Adult Adult Adult Adult Adult Adult Adult
## Levels: Child Adult</code></pre>
<p>This means we can access data with a column or row number. More importantly we can use the name. For large data frames accessing by a name is key.</p>
<div id="further-indexing" class="section level3">
<h3>Further Indexing</h3>
<p>Let’s say we wish to know information about a particular class</p>
<pre class="r"><code>titanic[&quot;1st&quot;, ]</code></pre>
<pre><code>##    Class  Sex  Age Survived Freq
## NA  &lt;NA&gt; &lt;NA&gt; &lt;NA&gt;     &lt;NA&gt;   NA</code></pre>
<p>We could also ask for information by using the factors that we have as well</p>
<pre class="r"><code>first.class.freq &lt;- titanic[titanic$Class==&quot;1st&quot;, &quot;Freq&quot;]
first.class.freq</code></pre>
<pre><code>## [1]   0   0 118   4   5   1  57 140</code></pre>
<pre class="r"><code>male.freq &lt;- titanic[titanic$Sex==&quot;Male&quot;, &quot;Freq&quot;]
male.freq</code></pre>
<pre><code>##  [1]   0   0  35   0 118 154 387 670   5  11  13   0  57  14  75 192</code></pre>
<p>Then we can add up the new values</p>
<pre class="r"><code>sum(first.class.freq)</code></pre>
<pre><code>## [1] 325</code></pre>
<pre class="r"><code>sum(male.freq)</code></pre>
<pre><code>## [1] 1731</code></pre>
</div>
</div>




<div class="content-box-blue">
<h1> Quick Check Practice</h1>   

 
  <div data-datacamp-exercise data-lang="r">
    <code data-type="pre-exercise-code">
set.seed(1234)
example = data.frame(c1=runif(50), c2=rnorm(50), c3=runif(50))
      </code>
        <code data-type="sample-code">
# 1.  How many observations are there in example? 



# 2. How many variables are there in example? 



# 3. What are the names of the variables in example?



# 4.  Create a dataframe with only observations where c1 > 0.2? Name this c1_gr_02.



# 5.  Create a dataframe with only observations where c1 > 0.2 and c2 > 0.2? Name this c1_c2_gr_02.
 
          </code>
          <code data-type="solution">
# 1.  How many observations are there in example? 

dim(example)[1]

# 2. How many variables are there in example? 

dim(example)[2]

# 3. What are the names of the variables in example?

names(example)

# 4.  Create a dataframe with only observations where c1 > 0.2? Name this c1_gr_02.

c1_gr_02 <- example[example$c1>0.2,]

# 5.  Create a dataframe with only observations where c1 > 0.2 and c2 > 0.2? Name this c1_c2_gr_02.

c1_c2_gr_02 <- example[example$c1>0.2 & example$c2>0.2,]


         </code>
              <code data-type="sct">
test_error()
test_function("dim")
test_function("dim")
test_function("names")
test_object("c1_gr_02", incorrect_msg = "Did you remember to name the new dataframe?")
test_object("c1_c2_gr_02",  incorrect_msg = "Did you remember to name the new dataframe?")
success_msg("Great Job")     </code>
              <div data-type="hint">Use your knowledge of dataframes to answer these questions.</div>
              </div>
</div>



<div id="adding-new-variables" class="section level2">
<h2>Adding New Variables</h2>
<p>Suppose we not only want to know the frequency of survival but the proportion. We can ask R to calculate this and add it to our data.</p>
<pre class="r"><code>titanic$surv_p &lt;- titanic$Freq/sum(titanic$Freq)
head(titanic,4)</code></pre>
<pre><code>##   Class  Sex   Age Survived Freq     surv_p
## 1   1st Male Child       No    0 0.00000000
## 2   2nd Male Child       No    0 0.00000000
## 3   3rd Male Child       No   35 0.01590186
## 4  Crew Male Child       No    0 0.00000000</code></pre>
<p>Perhaps we were not pleased the decimal places and want to have this as a percentage. We can overwrite the values and change this.</p>
<pre class="r"><code>titanic$surv_p &lt;- titanic$surv_p*100
head(titanic,4)</code></pre>
<pre><code>##   Class  Sex   Age Survived Freq   surv_p
## 1   1st Male Child       No    0 0.000000
## 2   2nd Male Child       No    0 0.000000
## 3   3rd Male Child       No   35 1.590186
## 4  Crew Male Child       No    0 0.000000</code></pre>
<p>In the future we will be performing many more operations on data frames.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();